# -*- coding: utf-8 -*-
import os
import sys

from appdirs import AppDirs


frkl_project_meta_app_dirs = AppDirs("frkl_project_meta", "frkl")

if not hasattr(sys, "frozen"):
    FRKL_PROJECT_META_MODULE_BASE_FOLDER = os.path.dirname(__file__)
    """Marker to indicate the base folder for the `frkl_project_meta` module."""
else:
    FRKL_PROJECT_META_MODULE_BASE_FOLDER = os.path.join(
        sys._MEIPASS, "frkl_project_meta"  # type: ignore
    )
    """Marker to indicate the base folder for the `frkl_project_meta` module."""

FRKL_PROJECT_META_RESOURCES_FOLDER = os.path.join(
    FRKL_PROJECT_META_MODULE_BASE_FOLDER, "resources"
)


PROJECT_META_DEFAULT_IGNORE_MODULES = [
    "zipp",
    "yaspin",
    "yarl",
    "whichcraft",
    "wheel",
    "wcwidth",
    "watchgod",
    "watchdog",
    "vistir",
    "virtualenv",
    "validators",
    "uvloop",
    "urllib3",
    "typing-extensions",
    "typed-ast",
    "treelib",
    "traitlets",
    "tox",
    "tornado",
    "toml",
    "text-unidecode",
    "stevedore",
    "sortedcontainers",
    "sniffio",
    "smmap",
    "six",
    "setuptools",
    "setuptools-scm",
    "scp",
    "scalpl",
    "s3transfer",
    "ruamel.yaml",
    "ruamel.yaml.clib",
    "rfc3986",
    "requests",
    "regex",
    "pyyaml",
    "pyupdater",
    "pyupdater-scp-plugin",
    "pyupdater-s3-plugin",
    "pytz",
    "python-slugify",
    "python-dateutil",
    "pytest",
    "pytest-cov",
    "pypubsub",
    "pyparsing",
    "pynacl",
    "pymdown-extensions",
    "pyinstaller",
    "pygments",
    "pyflakes",
    "pydriller",
    "pydantic",
    "pycparser",
    "pycodestyle",
    "py",
    "ptyprocess",
    "prompt-toolkit",
    "pp-ez",
    "poyo",
    "portray",
    "pluggy",
    "pkg-resources",
    "pipdeptree",
    "pip",
    "pip-tools",
    "pickleshare",
    "pexpect",
    "pdocs",
    "pbr",
    "pathtools",
    "pathspec",
    "parso",
    "paramiko",
    "packaging",
    "nuitka",
    "nodeenv",
    "nltk",
    "mypy",
    "mypy-extensions",
    "multidict",
    "more-itertools",
    "mkdocs",
    "mkdocs-material",
    "mccabe",
    "markupsafe",
    "markdown",
    "mako",
    "lunr",
    "logzero",
    "lizard",
    "livereload",
    "kubernetes-asyncio",
    "jmespath",
    "jinja2",
    "jinja2-time",
    "jedi",
    "isort",
    "ipython",
    "ipython-genutils",
    "importlib-resources",
    "importlib-metadata",
    "immutables",
    "idna",
    "idna-ssl",
    "identify",
    "hyperframe",
    "hug",
    "httpx",
    "hstspreload",
    "hpack",
    "h11",
    "h2",
    "gitpython",
    "gitdb",
    "future",
    "formic2",
    "flake8",
    "filelock",
    "fastavro",
    "falcon",
    "examples",
    "entrypoints",
    "ed25519",
    "dsdev-utils",
    "dpath",
    "docutils",
    "distlib",
    "dictdiffer",
    "decorator",
    "dataclasses",
    "cryptography",
    "cruft",
    "coverage",
    "cookiecutter",
    "contextvars",
    "colorama",
    "click",
    "click-aliases",
    "chardet",
    "cfgv",
    "cffi",
    "certifi",
    "pre-commit",
    "bsdiff4",
    "botocore",
    "boto3",
    "blessed",
    "black",
    "binaryornot",
    "bcrypt",
    "backcall",
    "attrs",
    "async-timeout",
    "async-generator",
    "async-exit-stack",
    "asgiref",
    "arrow",
    "appdirs",
    "anyio",
    "altgraph",
    "aiohttp",
    "frkl.jinja2schema",
    "asyncclick",
]
